services:
  api:
    deploy:
      resources:
        limits:
          memory: 10000M
        reservations:
          memory: 5000M
    build:
      context: .
      dockerfile: chatbot/Dockerfile.api
    image: react-flask-app-api
  client:
    build:
      context: .
      dockerfile: chatbot/Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"
