services:
  api:
    build:
      context: .
      dockerfile: chatbot/Dockerfile.api
    image: brock-chatbot-api
  web:
    build:
      context: .
      dockerfile: chatbot/Dockerfile.web
    image: brock-chatbot-web
    ports:
      - "80:80"
