# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

RUN apt-get update \
    && apt-get -y install libenchant-2-dev 

#COPY chatbot/api/requirements.txt chatbot/api/api.py chatbot/api/.flaskenv ./
COPY /chatbot/api ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV development

EXPOSE 5000
 #--log-level debug
CMD ["gunicorn", "-b", ":5000", "api:app", "--timeout 600"]
